"""memperbaiki

Revision ID: 183fc811960c
Revises: c345c0a96313
Create Date: 2024-04-13 12:41:58.385789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183fc811960c'
down_revision = 'c345c0a96313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misi',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('misi', sa.String(length=250), nullable=False),
    sa.Column('visiId', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['visiId'], ['visi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('misi')
    # ### end Alembic commands ###
