"""memperbaiki

Revision ID: c345c0a96313
Revises: 
Create Date: 2024-04-13 12:37:18.935714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c345c0a96313'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visi',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('visi', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('visi__misi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visi__misi',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('visi', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('misi', mysql.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('visi')
    # ### end Alembic commands ###
